version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/:/data/db

  products:
    image: usman64660/microservices:products-v1
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - mongo-db
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017/products
    volumes:
      - .:/app
      - /app/products/node_modules

  shopping:
    image: usman64660/microservices:shopping-v1
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - mongo-db
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017/shopping
    volumes:
      - .:/app
      - /app/shopping/node_modules

  customer:
    image: usman64660/microservices:customer-v1
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - mongo-db
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017/customer
    volumes:
      - .:/app
      - /app/customer/node_modules

  nginx-proxy:
    image: usman64660/microservices:proxy-v1
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - "80:80"

